# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic_regulation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18traffic_regulation.proto\x12\x04main\"\x8b\x01\n\x12TrafficDataForLogs\x12\x17\n\x0fintersection_id\x18\x01 \x01(\x05\x12\x17\n\x0fsignal_status_1\x18\x02 \x01(\x05\x12\x15\n\rvehicle_count\x18\x03 \x01(\x05\x12\x10\n\x08incident\x18\x04 \x01(\x08\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\t\"4\n!TrafficDataForLogsReceiveResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x1aIntersectionRequestForLogs\x12\x17\n\x0fintersection_id\x18\x01 \x01(\x05\"B\n\x19TrafficRegulationResponse\x12\x17\n\x0fintersection_id\x18\x01 \x01(\x05\x12\x0c\n\x04logs\x18\x02 \x03(\t\"D\n\x18\x41\x64\x64\x44\x61taRegulationRequest\x12\x17\n\x0fintersection_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x19\x41\x64\x64\x44\x61taRegulationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x1b\x44\x65leteDataRegulationRequest\x12\x17\n\x0fintersection_id\x18\x01 \x01(\x05\"/\n\x1c\x44\x65leteDataRegulationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n%TrafficRegulationServiceStatusRequest\"9\n&TrafficRegulationServiceStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd5\x04\n\x11TrafficRegulation\x12W\n\x12ReceiveDataForLogs\x12\x18.main.TrafficDataForLogs\x1a\'.main.TrafficDataForLogsReceiveResponse\x12T\n\x11\x41\x64\x64\x44\x61taRegulation\x12\x1e.main.AddDataRegulationRequest\x1a\x1f.main.AddDataRegulationResponse\x12]\n\x14\x44\x65leteDataRegulation\x12!.main.DeleteDataRegulationRequest\x1a\".main.DeleteDataRegulationResponse\x12X\n\x13GetTodayControlLogs\x12 .main.IntersectionRequestForLogs\x1a\x1f.main.TrafficRegulationResponse\x12[\n\x16GetLastWeekControlLogs\x12 .main.IntersectionRequestForLogs\x1a\x1f.main.TrafficRegulationResponse\x12{\n\x1eTrafficRegulationServiceStatus\x12+.main.TrafficRegulationServiceStatusRequest\x1a,.main.TrafficRegulationServiceStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_regulation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRAFFICDATAFORLOGS']._serialized_start=35
  _globals['_TRAFFICDATAFORLOGS']._serialized_end=174
  _globals['_TRAFFICDATAFORLOGSRECEIVERESPONSE']._serialized_start=176
  _globals['_TRAFFICDATAFORLOGSRECEIVERESPONSE']._serialized_end=228
  _globals['_INTERSECTIONREQUESTFORLOGS']._serialized_start=230
  _globals['_INTERSECTIONREQUESTFORLOGS']._serialized_end=283
  _globals['_TRAFFICREGULATIONRESPONSE']._serialized_start=285
  _globals['_TRAFFICREGULATIONRESPONSE']._serialized_end=351
  _globals['_ADDDATAREGULATIONREQUEST']._serialized_start=353
  _globals['_ADDDATAREGULATIONREQUEST']._serialized_end=421
  _globals['_ADDDATAREGULATIONRESPONSE']._serialized_start=423
  _globals['_ADDDATAREGULATIONRESPONSE']._serialized_end=467
  _globals['_DELETEDATAREGULATIONREQUEST']._serialized_start=469
  _globals['_DELETEDATAREGULATIONREQUEST']._serialized_end=523
  _globals['_DELETEDATAREGULATIONRESPONSE']._serialized_start=525
  _globals['_DELETEDATAREGULATIONRESPONSE']._serialized_end=572
  _globals['_TRAFFICREGULATIONSERVICESTATUSREQUEST']._serialized_start=574
  _globals['_TRAFFICREGULATIONSERVICESTATUSREQUEST']._serialized_end=613
  _globals['_TRAFFICREGULATIONSERVICESTATUSRESPONSE']._serialized_start=615
  _globals['_TRAFFICREGULATIONSERVICESTATUSRESPONSE']._serialized_end=672
  _globals['_TRAFFICREGULATION']._serialized_start=675
  _globals['_TRAFFICREGULATION']._serialized_end=1272
# @@protoc_insertion_point(module_scope)
