global:
  scrape_interval: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ['gateway:6060']
  - job_name: coordinator
    static_configs:
      - targets: ['coordinator:6061']
  - job_name: traffic-analytics-service
    static_configs:
      - targets: ['traffic-analytics-service-1:7001', 'traffic-analytics-service-2:7002', 'traffic-analytics-service-3:7003']
  - job_name: traffic-regulation-service
    static_configs:
      - targets: ['traffic-regulation-service-1:8001', 'traffic-regulation-service-2:8002', 'traffic-regulation-service-3:8003']
